services:
  postgres:
    image: postgres:16
    container_name: softpan-postgres
    environment:
      POSTGRES_USER: softpan
      POSTGRES_PASSWORD: Softpan123!
      POSTGRES_DB: SoftpanDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - softpan-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U softpan -d SoftpanDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: softpan-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=SoftpanDB;Username=softpan;Password=Softpan123!
      - MercadoPago__AccessToken=APP_USR-4993144536923832-051915-5fe764b7c6473da7a1269009d279baf7-3412374799
      - MercadoPago__BaseUrl=http://localhost:5173
      - MercadoPago__NotificationUrl=https://hunk-haven-escalator.ngrok-free.dev/api/mercadopago/webhook
      
    ports:
      - "7097:8080"
       # --- AGREGAR ESTO ---
    volumes:
      - ./images:/app/wwwroot/images
    # -------------------
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - softpan-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  softpan-network:
    driver: bridge
